services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api-auth
    ports:
      - "3317:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api_auth_network
  
  api-auth:
    build: .
    container_name: api-auth
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/api-auth
    ports:
      - "8899:8899"
    networks:
      - api_auth_network

volumes:
  db_data:

networks:
  api_auth_network:
    name: api_auth_network
    driver: bridge
