version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api-manager-pro
    ports:
      - "3317:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api_network
  
  api-manager:
    build: .
    container_name: api-manager
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/api-manager-pro
    ports:
      - "8899:8899"
    networks:
      - api_network

volumes:
  db_data:

networks:
  api_network:
    name: api_network
    driver: bridge
